import { Card } from '@/lib/types/game';

// 全カードは CARDS 配列で一元管理する。新カードはここに追加するだけ。
export const CARDS: Card[] = [
  {
    id: 'militia',
    name: '民兵',
    cost: 4,
    movement: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    attackRange: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    atk: 1,
    hp: 1,
  },
  {
    id: 'light_infantry',
    name: '軽歩兵',
    cost: 5,
    movement: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    attackRange: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    atk: 1,
    hp: 2,
  },
  {
    id: 'assault_soldier',
    name: '急襲兵',
    cost: 5,
    movement: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    attackRange: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    atk: 2,
    hp: 1,
  },
  {
    id: 'scout',
    name: '偵察兵',
    cost: 5,
    movement: { type: 'jump', offsets: [{ dx: 0, dy: -2 }] },
    attackRange: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    atk: 1,
    hp: 1,
  },
  {
    id: 'spear_soldier',
    name: '槍兵',
    cost: 6,
    movement: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    attackRange: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    atk: 2,
    hp: 2,
  },
  {
    id: 'heavy_infantry',
    name: '重装兵',
    cost: 7,
    movement: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    attackRange: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    atk: 1,
    hp: 4,
  },
  {
    id: 'combat_soldier',
    name: '戦闘兵',
    cost: 8,
    movement: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    attackRange: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    atk: 3,
    hp: 3,
  },
  {
    id: 'archer',
    name: '弓兵',
    cost: 11,
    movement: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    attackRange: { type: 'ranged', direction: { dx: 0, dy: -1 }, maxDistance: 2 },
    atk: 2,
    hp: 1,
    skill: {
      id: 'archer_penetrate',
      name: '貫通',
      description: 'ベース攻撃時、ダメージ+1（合計2）',
      effectType: 'penetrate',
      effectValue: 1,
      uses: 3,
    },
  },
  {
    id: 'guard',
    name: '衛兵',
    cost: 12,
    movement: {
      type: 'step',
      directions: [
        { dx: 0, dy: -1 }, { dx: 0, dy: 1 },
        { dx: -1, dy: 0 }, { dx: 1, dy: 0 },
      ],
    },
    attackRange: {
      type: 'step',
      directions: [
        { dx: 0, dy: -1 }, { dx: 0, dy: 1 },
        { dx: -1, dy: 0 }, { dx: 1, dy: 0 },
      ],
    },
    atk: 1,
    hp: 3,
  },
  {
    id: 'healer',
    name: '治癒兵',
    cost: 13,
    movement: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    attackRange: { type: 'none' },
    atk: 0,
    hp: 2,
    skill: {
      id: 'healer_heal',
      name: '治癒',
      description: '隣接する味方ユニット1体のHPを+2（最大HPは超えない）',
      effectType: 'heal',
      effectValue: 2,
      uses: 'infinite',
      range: {
        type: 'step',
        directions: [
          { dx: 0, dy: -1 }, { dx: 0, dy: 1 },
          { dx: -1, dy: 0 }, { dx: 1, dy: 0 },
        ],
      },
    },
  },
  {
    id: 'cavalry',
    name: '騎兵',
    cost: 14,
    movement: { type: 'jump', offsets: [{ dx: 0, dy: -2 }] },
    attackRange: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    atk: 4,
    hp: 3,
    skill: {
      id: 'cavalry_buff',
      name: '強化',
      description: '任意の味方ユニットのATKを永続的に+1',
      effectType: 'buff',
      effectValue: 1,
      uses: 1,
    },
  },
  {
    id: 'cannon',
    name: '大砲',
    cost: 17,
    movement: { type: 'step', directions: [{ dx: 0, dy: -1 }] },
    attackRange: { type: 'ranged', direction: { dx: 0, dy: -1 }, maxDistance: 4 },
    atk: 5,
    hp: 2,
    skill: {
      id: 'cannon_big_penetrate',
      name: '大貫通',
      description: 'ベース攻撃時、ダメージはATK分そのまま',
      effectType: 'big_penetrate',
      uses: 1,
    },
  },
  {
    id: 'defender',
    name: '守護兵',
    cost: 28,
    movement: {
      type: 'step',
      directions: [
        { dx: 0, dy: -1 }, { dx: 0, dy: 1 },
        { dx: -1, dy: 0 }, { dx: 1, dy: 0 },
      ],
    },
    attackRange: {
      type: 'step',
      directions: [
        { dx: 0, dy: -1 }, { dx: 0, dy: 1 },
        { dx: -1, dy: 0 }, { dx: 1, dy: 0 },
        { dx: -1, dy: -1 }, { dx: 1, dy: -1 },
        { dx: -1, dy: 1 }, { dx: 1, dy: 1 },
      ],
    },
    atk: 2,
    hp: 5,
    skill: {
      id: 'defender_counter',
      name: '反撃',
      description: '攻撃を受けた直後、攻撃元にATK分のダメージを与える',
      effectType: 'counter',
      uses: 'infinite',
    },
  },
];

export const CARD_MAP: Record<string, Card> = Object.fromEntries(
  CARDS.map((c) => [c.id, c])
);
