import type { StoryChapter } from './types';

export const CHAPTER1: StoryChapter = {
  chapterNum: 1,
  title: '第1章：エルナへの道',
  events: [
    // Scene 1-1: 鍛冶工房の朝
    { type: 'bg', id: 'forge_morning' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'calm' },
    { type: 'think', text: 'ここは……' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: '起きたか、ボウズ' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'あの、昨日はありがとうございました' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: '礼はいい。それより——' },
    { type: 'say', speaker: 'ブリギッタ', text: 'お前が昨日話していた『カード創造』ってスキル、あれ本当か？' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'はい' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: '……' },
    { type: 'say', speaker: 'ブリギッタ', text: 'この世界では、人は5歳でスキル鑑定を受ける' },
    { type: 'say', speaker: 'ブリギッタ', text: '1人1スキル、生涯固定' },
    { type: 'say', speaker: 'ブリギッタ', text: 'そのスキルで、人生がほぼ決まる' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: '1スキル……' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'あたしのスキルは『カード化』' },
    { type: 'say', speaker: 'ブリギッタ', text: 'これはレアな鍛冶系のスキルだ' },
    { type: 'say', speaker: 'ブリギッタ', text: 'スキル持ちが残した『写石（しゃせき）』を、誰でも使えるカードに加工する' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'スキルを写石（しゃせき）にして……カードを作る' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'そうだ' },
    { type: 'say', speaker: 'ブリギッタ', text: 'だから普通のカードスミスは、まず写石を買うところから始める' },
    { type: 'say', speaker: 'ブリギッタ', text: 'だが、お前は——写石も何も持たずに、いきなりカードを生み出した' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'はい……自分でも、よくわからないんですが' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'それは、伝説の中にしか存在しないやり方だ' },
    { type: 'say', speaker: 'ブリギッタ', text: '『コンセプト・スミス』って言うんだ' },
    { type: 'say', speaker: 'ブリギッタ', text: '500年前、世界を救って消えたっていう、神話みたいな存在' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'えっ' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'ま、お前が本物かどうかは、これから見ればわかる' },
    { type: 'say', speaker: 'ブリギッタ', text: 'あたしの工房で、鍛冶を学んでみろ' },
    { type: 'say', speaker: 'ブリギッタ', text: '無理にとは言わねえが——' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'やります！' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: '即決か' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'いいだろう。今日からお前はあたしの弟子だ' },
    { type: 'say', speaker: 'ブリギッタ', text: 'とりあえず、街まで一緒に来い' },
    { type: 'say', speaker: 'ブリギッタ', text: 'あたしの噂を聞いた連中が、最近この辺で物騒なことしてやがる' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: '物騒？' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'ま、護衛代わりにお前の力を見せてみろ' },
    { type: 'say', speaker: 'ブリギッタ', text: 'あと、それ1枚だけじゃ心もとないだろ、これを渡しておく' },
    { type: 'exit', char: 'brigitta' },
    { type: 'system', text: '「見習い騎士ノア」と「誓いの剣士アイロス」を1枚ずつ受け取った！' },

    // Scene 1-2: 街道バトル
    { type: 'bg', id: 'road_forest' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'calm' },
    { type: 'think', text: '街道は森の中を抜ける細い道' },
    { type: 'think', text: '確かに、物騒な雰囲気だ' },
    { type: 'exit', char: 'player' },
    { type: 'narrate', text: '（足音、複数）' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: '来たな' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'えっ、また野盗ですか！？' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'あたしは見てるだけだ' },
    { type: 'say', speaker: 'ブリギッタ', text: 'お前のカード、もう一度見せてみな' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'はい！' },
    { type: 'battle', questId: 'story_1_2' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'お前のカード、本当に強いな……' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'すみません、本当に何も分かってないので……' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'いいさ。これからゆっくり覚えな' },
    { type: 'say', speaker: 'ブリギッタ', text: '街に着いたら、まず街を見せる' },

    // Scene 1-3: エルナの街
    { type: 'bg', id: 'elna_city' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'surprised' },
    { type: 'think', text: 'これが異世界の街……' },
    { type: 'think', text: '中世ヨーロッパっぽい感じだけど、なんか違う' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: '商人の声、聞いとけ。この世界の経済の基本だ' },
    { type: 'exit', char: 'brigitta' },
    { type: 'narrate', text: '商人「ヘイヘイ、新しい冷蔵カード入ったよ！」' },
    { type: 'narrate', text: '主婦「あら、火起こしカードの予備、買っとかなきゃ」' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'surprised' },
    { type: 'think', text: '冷蔵カード？火起こしカード？' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'カードってのはな、戦闘用だけじゃない' },
    { type: 'say', speaker: 'ブリギッタ', text: '冷蔵、火起こし、水浄化、医療、輸送——ぜんぶカードだ' },
    { type: 'say', speaker: 'ブリギッタ', text: '人々は毎日カードを買って生活してる' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'すごい……' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'surprised' },
    { type: 'think', text: 'あの人……顔色が悪い' },
    { type: 'exit', char: 'player' },
    { type: 'narrate', text: '写畜「今日も写石（しゃせき）を売ってきた……」' },
    { type: 'narrate', text: '写畜「あと何回、写せるだろうか」' },
    { type: 'narrate', text: '写畜「ゲホッ、ゲホッ」' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'あの人……' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: '『写畜（しゃちく）』だ' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: '写畜……？' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: '自分のスキルを『空の写石』に写して、毎日売って生活する人々' },
    { type: 'say', speaker: 'ブリギッタ', text: '写すたびに、生命力が削られていく' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'なんだって！？命を削る？' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: '写石ってのは、人の命の一部を写し取ったものだからな' },
    { type: 'say', speaker: 'ブリギッタ', text: '希少なスキル持ちは、買い手が金を惜しまない' },
    { type: 'say', speaker: 'ブリギッタ', text: 'だから一回の取引で、しっかり稼げる' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: '希少だと、儲かる……' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'だが、ありきたりなスキルしか持っちゃいない奴は、安く買い叩かれる' },
    { type: 'say', speaker: 'ブリギッタ', text: 'だから何度も写さねえと、生活できない' },
    { type: 'say', speaker: 'ブリギッタ', text: '結果——早く生命力を使い切って、若くして死んでいく' },
    { type: 'say', speaker: 'ブリギッタ', text: 'この世界では当たり前のことさ' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'そんな……' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'あたしが作るカードの写石も——' },
    { type: 'say', speaker: 'ブリギッタ', text: '誰かの命の一部だ' },
    { type: 'say', speaker: 'ブリギッタ', text: '忘れんなよ' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: '行くぞ' },

    // Scene 1-4: 路地裏
    { type: 'bg', id: 'elna_alley' },
    { type: 'narrate', text: '（路地裏で、ゴロツキ3人が写畜を威嚇している）' },
    { type: 'narrate', text: 'ゴロツキ「おら、今日の写石よこせ」' },
    { type: 'narrate', text: '写畜「今日はもう、これ以上写したら命が……」' },
    { type: 'narrate', text: 'ゴロツキ「うるせえ！」' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'やめろ！' },
    { type: 'battle', questId: 'story_1_4' },
    { type: 'narrate', text: 'ゴロツキ「ち、化け物だ！逃げろ！」' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: '大丈夫ですか？' },
    { type: 'exit', char: 'player' },
    { type: 'narrate', text: '写畜「ありがとうございます……」' },
    { type: 'narrate', text: '写畜「今日の写石、それを売らないと、子供のパンが……」' },
    { type: 'narrate', text: '写畜「でも、もう写せる命が……」' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'calm' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'これがこの世界だ、ボウズ' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'think', text: 'もっと、何かできることが……' },

    // Scene 1-5: ニケとの出会い
    { type: 'bg', id: 'elna_square' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'calm' },
    { type: 'think', text: '街を歩いていると、子供たちの集まりが……' },
    { type: 'exit', char: 'player' },
    { type: 'narrate', text: '子供A「植物の声を聞くスキル？　なに、それ。役立たずじゃん」' },
    { type: 'narrate', text: '子供B「お前のお母さん、写畜でしょ？　もうすぐ死ぬんでしょ？」' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'やめろ！' },
    { type: 'narrate', text: '（子供たちが手にした「いたずらカード」を構える）' },
    { type: 'battle', questId: 'story_1_5' },
    { type: 'narrate', text: '（子供たちが逃げ出す）' },
    { type: 'enter', char: 'nike', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: 'ニケ', text: 'あ、あの……' },
    { type: 'exit', char: 'nike' },
    { type: 'enter', char: 'player', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: '大丈夫？　怪我はない？' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'nike', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: 'ニケ', text: 'はい……ありがとうございます' },
    { type: 'say', speaker: 'ニケ', text: 'いつものことなので、大丈夫です' },
    { type: 'exit', char: 'nike' },
    { type: 'enter', char: 'player', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'いつもの……？' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'nike', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: 'ニケ', text: '私のスキル、『植物の声を聞く』っていうコモンなんです' },
    { type: 'say', speaker: 'ニケ', text: '役に立たないって、よくいじめられて' },
    { type: 'exit', char: 'nike' },
    { type: 'enter', char: 'player', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: '役に立たないなんて、そんなことない' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'nike', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: 'ニケ', text: 'えっ……' },
    { type: 'exit', char: 'nike' },
    { type: 'enter', char: 'player', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: '植物の声が聞けるって、すごいことじゃないかな' },
    { type: 'say', speaker: '主人公', text: '僕には、そんなことできないし' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'nike', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: 'ニケ', text: 'そんなふうに言ってもらえたの、初めてです' },
    { type: 'exit', char: 'nike' },
    { type: 'enter', char: 'player', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: '冒険者って言います' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'nike', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: 'ニケ', text: '私、ニケ！　ニケ・ヴィエンタ！' },
    { type: 'say', speaker: 'ニケ', text: 'あの、もしよかったら、うちに寄ってもらえませんか？' },
    { type: 'say', speaker: 'ニケ', text: 'お母さんが最近体調悪くて、人に会いたいって言ってて' },
    { type: 'exit', char: 'nike' },
    { type: 'enter', char: 'player', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'うん、ぜひ' },

    { type: 'end', chapterNum: 1 },
  ],
};
