import type { StoryChapter } from './types';

export const CHAPTER0: StoryChapter = {
  chapterNum: 0,
  title: '第0章：転生の日',
  events: [
    // Scene 0-1: 神との対話
    { type: 'bg', id: 'divine' },
    { type: 'enter', char: 'god', pos: 'center', expr: 'smile' },
    { type: 'say', speaker: '神', text: 'やっほー、君、転生する子だよね？' },
    { type: 'think', text: '……え？' },
    { type: 'exit', char: 'god' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'あなたが……神様？' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'god', pos: 'left', expr: 'smile' },
    { type: 'say', speaker: '神', text: 'ちょっと違うかも？まあ神様って言えば神様かな！' },
    { type: 'say', speaker: '神', text: '私もよくわかんないんだよねー、自分のこと' },
    { type: 'exit', char: 'god' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'think', text: '神様なのにわかんないって……' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'god', pos: 'left', expr: 'smile' },
    { type: 'say', speaker: '神', text: 'とにかく、君に異世界行ってもらうから〜' },
    { type: 'exit', char: 'god' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'えっ、転生するんですか僕' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'god', pos: 'left', expr: 'smile' },
    { type: 'say', speaker: '神', text: 'そうそう、もう死んじゃったし' },
    { type: 'exit', char: 'god' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'えっ……' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'god', pos: 'left', expr: 'smile' },
    { type: 'say', speaker: '神', text: 'あ、しまった、配慮がなかった！' },
    { type: 'say', speaker: '神', text: 'ごめんごめん、でも前向きに行こう！　次の人生だよ！' },
    { type: 'exit', char: 'god' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: '……はい' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'god', pos: 'left', expr: 'smile' },
    { type: 'say', speaker: '神', text: 'で、君に特別なスキル渡すよ！' },
    { type: 'say', speaker: '神', text: 'その名も……『カード創造』！' },
    { type: 'exit', char: 'god' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'カード、創造……' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'god', pos: 'left', expr: 'smile' },
    { type: 'say', speaker: '神', text: '君は何でも作れる。何でも生み出せる' },
    { type: 'say', speaker: '神', text: '異世界には『カードスミス』って職業があってね' },
    { type: 'say', speaker: '神', text: 'みんなは写石から作るんだけど、君は違う' },
    { type: 'say', speaker: '神', text: '君は——自分の頭の中にあるものから、カードを作れる' },
    { type: 'exit', char: 'god' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: '頭の中の……？' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'god', pos: 'left', expr: 'smile' },
    { type: 'say', speaker: '神', text: 'そう！　じゃあ、ためしに1枚作ってみよっか' },

    // Scene 0-2: カード創造
    { type: 'card_create' },
    { type: 'enter', char: 'god', pos: 'left', expr: 'smile' },
    { type: 'say', speaker: '神', text: 'おおー、すごいカード作ったね！' },
    { type: 'say', speaker: '神', text: '『{firstCardName}』だって。なんかいい名前' },
    { type: 'exit', char: 'god' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'think', text: '（カードを見つめる）' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'god', pos: 'left', expr: 'smile' },
    { type: 'say', speaker: '神', text: '異世界の鍛冶師は驚くと思うよ、こんなカード見たら' },
    { type: 'exit', char: 'god' },
    { type: 'enter', char: 'god', pos: 'left', expr: 'smile' },
    { type: 'say', speaker: '神', text: 'じゃ、行ってらっしゃーい♪' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'ちょ、待っ——' },
    { type: 'exit', char: 'god' },
    { type: 'exit', char: 'player' },
    { type: 'transition', effect: 'whiteout' },

    // Scene 0-3: 異世界転生
    { type: 'bg', id: 'field_day' },
    { type: 'think', text: 'うっ……ここは……' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: '森……？　草原……？' },
    { type: 'say', speaker: '主人公', text: '異世界……本当に……' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'とりあえず、街を探さないと——' },
    { type: 'exit', char: 'player' },
    { type: 'narrate', text: '（足音が複数、周囲から）' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: '！？' },
    { type: 'exit', char: 'player' },
    { type: 'think', text: '野盗だ……取り囲まれてる' },
    { type: 'narrate', text: '野盗「へへへ……いい服着てるみたいだな」' },
    { type: 'narrate', text: '野盗「俺は強いカードを持ってるからよぉ」' },
    { type: 'narrate', text: '野盗「さっさと服脱いで、金置いていけや」' },
    { type: 'enter', char: 'player', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'さっき創造したこのカード……' },
    { type: 'say', speaker: '主人公', text: 'やってみるしかない！' },

    // Scene 0-4: バトル
    { type: 'battle', questId: 'story_0_4' },
    { type: 'narrate', text: '野盗「なんだあのカード……強すぎるだろぉ！？」' },
    { type: 'narrate', text: '野盗「やべぇぞ、逃げろ！！」' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'は、はあっ……勝った……？' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'player', pos: 'center', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: '本当に……カード創造、効くんだ……' },
    { type: 'exit', char: 'player' },
    { type: 'narrate', text: '（誰かの足音が近づいてくる）' },

    // Scene 0-5: ブリギッタとの出会い
    { type: 'bg', id: 'field_dusk' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: '……ほう' },
    { type: 'say', speaker: 'ブリギッタ', text: 'ボウズ、お前……今、何をした？' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'えっ、あの……戦って……' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'カード召喚は見えた' },
    { type: 'say', speaker: 'ブリギッタ', text: 'だが、お前——見たことのないカードだな、カードスミスか？' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'カードスミス……？' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'カードスミスを知らねえだと？' },
    { type: 'say', speaker: 'ブリギッタ', text: 'お前、見たところスキル鑑定も受けてねえな' },
    { type: 'say', speaker: 'ブリギッタ', text: '服装も、この国のじゃない' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'calm' },
    { type: 'say', speaker: '主人公', text: 'あの、僕……どこから来たかも、よくわからなくて' },
    { type: 'say', speaker: '主人公', text: '神様にスキルをもらって、転生してきました' },
    { type: 'say', speaker: '主人公', text: 'このカードも、カード創造というスキルで生み出したものです' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: '神様？カード創造？？' },
    { type: 'say', speaker: 'ブリギッタ', text: '一体何の話をしてるんだ？' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: '……ま、いい' },
    { type: 'say', speaker: 'ブリギッタ', text: 'あたしの工房に来な' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'えっ' },
    { type: 'exit', char: 'player' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'お前のそのカード' },
    { type: 'say', speaker: 'ブリギッタ', text: 'あたしの知ってるカードスミスの作品じゃねぇ' },
    { type: 'say', speaker: 'ブリギッタ', text: '気になっちまった' },
    { type: 'exit', char: 'brigitta' },
    { type: 'enter', char: 'brigitta', pos: 'left', expr: 'calm' },
    { type: 'say', speaker: 'ブリギッタ', text: 'ついて来い、ボウズ' },
    { type: 'enter', char: 'player', pos: 'right', expr: 'surprised' },
    { type: 'say', speaker: '主人公', text: 'あ、はい！　あ、待ってください！' },

    { type: 'end', chapterNum: 0, nextChapter: 1 },
  ],
};
